<a href="https://colab.research.google.com/github/Abdul-Haseeb-boonig/20NewsGroups_Classification_CNN/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Difference between X_test, X_train, y_test, y_train

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.33,
                                                    random_state = 42)

In [7]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [8]:
y_train

[2, 0, 3]

In [9]:
X_test

array([[2, 3],
       [8, 9]])

In [10]:
y_test

[1, 4]

In [ ]:
train_test_split(y, shuffle = False)